# Generated by Django 4.2.2 on 2023-06-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_rename_name_oficialaria_nome_capitulo'),
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrivao',
            name='capitulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizacao.capitulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrocapitulo',
            name='capitulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizacao.capitulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mestreconselheiro',
            name='capitulo',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='organizacao.capitulo'),
            preserve_default=False,
        ),
    ]
