# Generated by Django 4.2.2 on 2023-06-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0001_initial'),
        ('organizacao', '0003_rename_endereco_capitulo_logadouro_capitulo_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuniaoCastelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacao.castelo')),
                ('membros_presentes', models.ManyToManyField(to='membros.membrocastelo')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
